/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as ConfirmarRouteImport } from './routes/confirmar'
import { Route as LocalRouteImport } from './routes/local'
import { Route as PagamentoRouteImport } from './routes/pagamento'
import { Route as PresentesRouteImport } from './routes/presentes'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiMercadoPagoRouteImport } from './routes/api.mercado-pago'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmarRoute = ConfirmarRouteImport.update({
  id: '/confirmar',
  path: '/confirmar',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalRoute = LocalRouteImport.update({
  id: '/local',
  path: '/local',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoRoute = PagamentoRouteImport.update({
  id: '/pagamento',
  path: '/pagamento',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentesRoute = PresentesRouteImport.update({
  id: '/presentes',
  path: '/presentes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiMercadoPagoRoute = ApiMercadoPagoRouteImport.update({
  id: '/api/mercado-pago',
  path: '/api/mercado-pago',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/carrinho': typeof CarrinhoRoute
  '/confirmar': typeof ConfirmarRoute
  '/local': typeof LocalRoute
  '/pagamento': typeof PagamentoRoute
  '/presentes': typeof PresentesRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/api/mercado-pago': typeof ApiMercadoPagoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/carrinho': typeof CarrinhoRoute
  '/confirmar': typeof ConfirmarRoute
  '/local': typeof LocalRoute
  '/pagamento': typeof PagamentoRoute
  '/presentes': typeof PresentesRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/api/mercado-pago': typeof ApiMercadoPagoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/carrinho': typeof CarrinhoRoute
  '/confirmar': typeof ConfirmarRoute
  '/local': typeof LocalRoute
  '/pagamento': typeof PagamentoRoute
  '/presentes': typeof PresentesRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/api/mercado-pago': typeof ApiMercadoPagoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/carrinho'
    | '/confirmar'
    | '/local'
    | '/pagamento'
    | '/presentes'
    | '/admin'
    | '/api/mercado-pago'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/carrinho'
    | '/confirmar'
    | '/local'
    | '/pagamento'
    | '/presentes'
    | '/admin'
    | '/api/mercado-pago'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/carrinho'
    | '/confirmar'
    | '/local'
    | '/pagamento'
    | '/presentes'
    | '/_authenticated/admin'
    | '/api/mercado-pago'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CarrinhoRoute: typeof CarrinhoRoute
  ConfirmarRoute: typeof ConfirmarRoute
  LocalRoute: typeof LocalRoute
  PagamentoRoute: typeof PagamentoRoute
  PresentesRoute: typeof PresentesRoute
  ApiMercadoPagoRoute: typeof ApiMercadoPagoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmar': {
      id: '/confirmar'
      path: '/confirmar'
      fullPath: '/confirmar'
      preLoaderRoute: typeof ConfirmarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local': {
      id: '/local'
      path: '/local'
      fullPath: '/local'
      preLoaderRoute: typeof LocalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento': {
      id: '/pagamento'
      path: '/pagamento'
      fullPath: '/pagamento'
      preLoaderRoute: typeof PagamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presentes': {
      id: '/presentes'
      path: '/presentes'
      fullPath: '/presentes'
      preLoaderRoute: typeof PresentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/mercado-pago': {
      id: '/api/mercado-pago'
      path: '/api/mercado-pago'
      fullPath: '/api/mercado-pago'
      preLoaderRoute: typeof ApiMercadoPagoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CarrinhoRoute: CarrinhoRoute,
  ConfirmarRoute: ConfirmarRoute,
  LocalRoute: LocalRoute,
  PagamentoRoute: PagamentoRoute,
  PresentesRoute: PresentesRoute,
  ApiMercadoPagoRoute: ApiMercadoPagoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
